# Generated by Django 4.1.3 on 2022-12-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('city', models.CharField(max_length=500, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('zipcode', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True, unique=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Client',
            },
        ),
        migrations.CreateModel(
            name='FromDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('website', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=25, null=True)),
            ],
            options={
                'verbose_name_plural': 'Main Admin',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, null=True)),
                ('rate', models.FloatField(default=0, null=True)),
                ('aditional_details', models.CharField(max_length=500, null=True)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
    ]
