# Generated by Django 4.1.3 on 2022-12-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='fromdetails',
            name='pincode',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
