# Generated by Django 4.1.3 on 2022-12-10 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_fromdetails_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('item_total', models.FloatField(default=0, null=True)),
                ('tax_amount', models.FloatField(default=0, null=True)),
                ('grand_total', models.FloatField(default=0, null=True)),
                ('note', models.CharField(max_length=2000, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.client')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('tax_applied', models.BooleanField(default=True)),
                ('itemtotal', models.FloatField(default=0)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.items')),
            ],
        ),
    ]
