# Generated by Django 4.1.3 on 2022-12-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_invoiceitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitems',
            name='tax_applied',
        ),
    ]
