# Generated by Django 4.1.3 on 2022-12-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_billpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.FloatField(default=0, null=True),
        ),
    ]
