# Generated by Django 4.1.3 on 2022-12-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoice_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='item_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.FloatField(default=0),
        ),
    ]
